<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net5.0</TargetFrameworks>
    <AssemblyName>Test.Amqp.Net</AssemblyName>
    <RootNamespace>Test.Amqp.Net</RootNamespace>
	<IsTestProject>true</IsTestProject>
	<IsPackable>false</IsPackable>
    <DefineConstants>$(DefineConstants);NETFX</DefineConstants>
    <IntermediateOutputPath>..\obj\$(Configuration)\$(MSBuildProjectName)\</IntermediateOutputPath>
    <OutputPath>..\bin\$(Configuration)\$(MSBuildProjectName)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- Test classes stay visible at project root. -->
    <Compile Include="../Common/*Tests.cs">
      <Link>%(Filename)%(Extension)</Link>
    </Compile>
    <!-- Supporting/helper files grouped under Include. -->
    <Compile Include="../Common/*.cs" Exclude="../Common/*Tests.cs">
      <Link>Include\%(Filename)%(Extension)</Link>
    </Compile>
    <Compile Include="../Common/Types/*.cs">
      <Link>Include\%(Filename)%(Extension)</Link>
    </Compile>
    <Compile Include="../../src/Net/TypeExtensions.cs">
      <Link>Include\TypeExtensions.cs</Link>
    </Compile>
    <Compile Include="../../Examples/Serialization/Serialization.Poco/PocoContractResolver.cs">
      <Link>Include\PocoContractResolver.cs</Link>
    </Compile>
    <Compile Include="../../Examples/Serialization/Serialization.Poco/Shape.cs">
      <Link>Include\Shape.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Reference Condition="'$(TargetFramework)' == 'net48'" Include="System.Transactions" />
  </ItemGroup>
	<ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
	<PackageReference Include="MSTest.TestAdapter" Version="3.4.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.4.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Amqp.Net.csproj" />
  </ItemGroup>
</Project>
